name: Bug report
description: Report an issue with the resource pack
title: 'Bug report: '
labels: ['bug']
assignees:
  - youngmani
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is, and steps to reproduce the issue.
      placeholder: ex. When I try to use the resource pack, I get an error message.
    validations:
      required: true
  - type: input
    id: minecraft-version
    attributes:
      label: Minecraft version
      description: The version of Minecraft you are using.
      placeholder: ex. Java Edition 1.21.4
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here, if applicable.
    validations:
      required: false
