'use strict';

// list of paintings to generate kz.png
module.exports = [
  { name: 'kebab', x: 0, y: 0, h: 1, w: 1 },
  { name: 'aztec', x: 1, y: 0, h: 1, w: 1 },
  { name: 'alban', x: 2, y: 0, h: 1, w: 1 },
  { name: 'aztec2', x: 3, y: 0, h: 1, w: 1 },
  { name: 'bomb', x: 4, y: 0, h: 1, w: 1 },
  { name: 'plant', x: 5, y: 0, h: 1, w: 1 },
  { name: 'wasteland', x: 6, y: 0, h: 1, w: 1 },
  { name: 'pool', x: 0, y: 2, h: 1, w: 2 },
  { name: 'courbet', x: 2, y: 2, h: 1, w: 2 },
  { name: 'sea', x: 4, y: 2, h: 1, w: 2 },
  { name: 'sunset', x: 6, y: 2, h: 1, w: 2 },
  { name: 'creebet', x: 8, y: 2, h: 1, w: 2 },
  { name: 'wanderer', x: 0, y: 4, h: 2, w: 1 },
  { name: 'graham', x: 1, y: 4, h: 2, w: 1 },
  { name: 'fighters', x: 0, y: 6, h: 2, w: 4 },
  { name: 'match', x: 0, y: 8, h: 2, w: 2 },
  { name: 'bust', x: 2, y: 8, h: 2, w: 2 },
  { name: 'stage', x: 4, y: 8, h: 2, w: 2 },
  { name: 'void', x: 6, y: 8, h: 2, w: 2 },
  { name: 'skull_and_roses', x: 8, y: 8, h: 2, w: 2 },
  { name: 'wither', x: 10, y: 8, h: 2, w: 2 },
  { name: 'pointer', x: 0, y: 12, h: 4, w: 4 },
  { name: 'pigscene', x: 4, y: 12, h: 4, w: 4 },
  { name: 'burning_skull', x: 8, y: 12, h: 4, w: 4 },
  { name: 'skeleton', x: 12, y: 4, h: 3, w: 4 },
  { name: 'donkey_kong', x: 12, y: 7, h: 3, w: 4 },
];
