name: Build and Release

on: [push]



jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IS_RELEASE: ${{ startsWith(github.ref, 'refs/tags/') }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: npm ci
      - if: env.IS_RELEASE == 'true'
        run: npm run build
      - if: env.IS_RELEASE == 'false'
        run: npm run build:dev
      - name: Draft release
        if: env.IS_RELEASE == 'true'
        uses: ncipollo/release-action@v1
        with:
          artifacts: build/*
          artifactContentType: application/zip
          draft: true
          generateReleaseNotes: true
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build/
          retention-days: 3
